// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: article.sql

package repository

import (
	"context"
	"time"
)

const addArticleTag = `-- name: AddArticleTag :exec
INSERT INTO article_tags (
    article_id, tag_id
) VALUES (
    $1, $2
)
ON CONFLICT DO NOTHING
`

type AddArticleTagParams struct {
	ArticleID int64 `json:"article_id"`
	TagID     int64 `json:"tag_id"`
}

func (q *Queries) AddArticleTag(ctx context.Context, arg AddArticleTagParams) error {
	_, err := q.db.Exec(ctx, addArticleTag, arg.ArticleID, arg.TagID)
	return err
}

const clearArticleTags = `-- name: ClearArticleTags :exec
DELETE FROM article_tags
WHERE
    article_id = $1
`

func (q *Queries) ClearArticleTags(ctx context.Context, articleID int64) error {
	_, err := q.db.Exec(ctx, clearArticleTags, articleID)
	return err
}

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (
    slug, title, description, body, author_id
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, slug, title, description, body, author_id, created_at, updated_at
`

type CreateArticleParams struct {
	Slug        string `json:"slug"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Body        string `json:"body"`
	AuthorID    int64  `json:"author_id"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (*Article, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Body,
		arg.AuthorID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Body,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
    article_id, author_id, body
) VALUES (
    $1, $2, $3
)
RETURNING id, article_id, author_id, body, created_at, updated_at
`

type CreateCommentParams struct {
	ArticleID int64  `json:"article_id"`
	AuthorID  int64  `json:"author_id"`
	Body      string `json:"body"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (*Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.ArticleID, arg.AuthorID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles
WHERE
    slug = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deleteArticle, slug)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments
WHERE
    id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const favoriteArticle = `-- name: FavoriteArticle :exec
INSERT INTO favorites (
    user_id, article_id
) VALUES (
    $1, $2
)
ON CONFLICT DO NOTHING
`

type FavoriteArticleParams struct {
	UserID    int64 `json:"user_id"`
	ArticleID int64 `json:"article_id"`
}

func (q *Queries) FavoriteArticle(ctx context.Context, arg FavoriteArticleParams) error {
	_, err := q.db.Exec(ctx, favoriteArticle, arg.UserID, arg.ArticleID)
	return err
}

const findArticleRefBySlug = `-- name: FindArticleRefBySlug :one
SELECT
    id, author_id
FROM
    articles
WHERE
    slug = $1
`

type FindArticleRefBySlugRow struct {
	ID       int64 `json:"id"`
	AuthorID int64 `json:"author_id"`
}

func (q *Queries) FindArticleRefBySlug(ctx context.Context, slug string) (*FindArticleRefBySlugRow, error) {
	row := q.db.QueryRow(ctx, findArticleRefBySlug, slug)
	var i FindArticleRefBySlugRow
	err := row.Scan(&i.ID, &i.AuthorID)
	return &i, err
}

const findCommentRefByID = `-- name: FindCommentRefByID :one
SELECT
    article_id, author_id
FROM
    comments
WHERE
    id = $1
`

type FindCommentRefByIDRow struct {
	ArticleID int64 `json:"article_id"`
	AuthorID  int64 `json:"author_id"`
}

func (q *Queries) FindCommentRefByID(ctx context.Context, id int64) (*FindCommentRefByIDRow, error) {
	row := q.db.QueryRow(ctx, findCommentRefByID, id)
	var i FindCommentRefByIDRow
	err := row.Scan(&i.ArticleID, &i.AuthorID)
	return &i, err
}

const getArticleBySlug = `-- name: GetArticleBySlug :one
SELECT
    a.slug,
    a.title,
    a.description,
    a.body,
    a.created_at,
    a.updated_at,
    u.username AS author_username,
    u.bio AS author_bio,
    u.image AS author_image,
    EXISTS (
        SELECT 1
        FROM follows f
        WHERE f.follower_id = $1
          AND f.followee_id = u.id
    ) AS author_following,
    EXISTS (
        SELECT 1
        FROM favorites fav
        WHERE fav.user_id = $1
          AND fav.article_id = a.id
    ) AS favorited,
    (
        SELECT COUNT(*)
        FROM favorites fav
        WHERE fav.article_id = a.id
    ) AS favorites_count,
    COALESCE(
        ARRAY_AGG(t.name ORDER BY t.name) FILTER (WHERE t.name IS NOT NULL),
        '{}'
    )::TEXT[] AS tag_list
FROM
    articles a
    JOIN users u ON u.id = a.author_id
    LEFT JOIN article_tags at2 ON at2.article_id = a.id
    LEFT JOIN tags t ON t.id = at2.tag_id
WHERE
    a.slug = $2
GROUP BY
    a.id, u.id, u.username, u.bio, u.image
`

type GetArticleBySlugParams struct {
	CurrentUserID *int64 `json:"current_user_id"`
	Slug          string `json:"slug"`
}

type GetArticleBySlugRow struct {
	Slug            string    `json:"slug"`
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	Body            string    `json:"body"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	AuthorUsername  string    `json:"author_username"`
	AuthorBio       *string   `json:"author_bio"`
	AuthorImage     *string   `json:"author_image"`
	AuthorFollowing bool      `json:"author_following"`
	Favorited       bool      `json:"favorited"`
	FavoritesCount  int64     `json:"favorites_count"`
	TagList         []string  `json:"tag_list"`
}

func (q *Queries) GetArticleBySlug(ctx context.Context, arg GetArticleBySlugParams) (*GetArticleBySlugRow, error) {
	row := q.db.QueryRow(ctx, getArticleBySlug, arg.CurrentUserID, arg.Slug)
	var i GetArticleBySlugRow
	err := row.Scan(
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorUsername,
		&i.AuthorBio,
		&i.AuthorImage,
		&i.AuthorFollowing,
		&i.Favorited,
		&i.FavoritesCount,
		&i.TagList,
	)
	return &i, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT
    c.id,
    c.body,
    c.created_at,
    c.updated_at,
    u.username AS author_username,
    u.bio AS author_bio,
    u.image AS author_image,
    EXISTS (
        SELECT 1
        FROM follows f
        WHERE f.follower_id = $1
          AND f.followee_id = u.id
    ) AS author_following
FROM
    comments c
    JOIN users u ON u.id = c.author_id
WHERE
    c.id = $2
`

type GetCommentByIDParams struct {
	CurrentUserID *int64 `json:"current_user_id"`
	ID            int64  `json:"id"`
}

type GetCommentByIDRow struct {
	ID              int64     `json:"id"`
	Body            string    `json:"body"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	AuthorUsername  string    `json:"author_username"`
	AuthorBio       *string   `json:"author_bio"`
	AuthorImage     *string   `json:"author_image"`
	AuthorFollowing bool      `json:"author_following"`
}

func (q *Queries) GetCommentByID(ctx context.Context, arg GetCommentByIDParams) (*GetCommentByIDRow, error) {
	row := q.db.QueryRow(ctx, getCommentByID, arg.CurrentUserID, arg.ID)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorUsername,
		&i.AuthorBio,
		&i.AuthorImage,
		&i.AuthorFollowing,
	)
	return &i, err
}

const listArticles = `-- name: ListArticles :many
SELECT
    a.slug,
    a.title,
    a.description,
    a.created_at,
    a.updated_at,
    u.username AS author_username,
    u.bio AS author_bio,
    u.image AS author_image,
    EXISTS (
        SELECT 1
        FROM follows f
        WHERE f.follower_id = $1
          AND f.followee_id = u.id
    ) AS author_following,
    EXISTS (
        SELECT 1
        FROM favorites fav
        WHERE fav.user_id = $1
          AND fav.article_id = a.id
    ) AS favorited,
    (
        SELECT COUNT(*)
        FROM favorites fav
        WHERE fav.article_id = a.id
    ) AS favorites_count,
    COALESCE(
        ARRAY_AGG(t.name ORDER BY t.name) FILTER (WHERE t.name IS NOT NULL),
        '{}'
    )::TEXT[] AS tag_list,
    COUNT(*) OVER ()::BIGINT AS total_count
FROM
    articles a
    JOIN users u ON u.id = a.author_id
    LEFT JOIN article_tags at2 ON at2.article_id = a.id
    LEFT JOIN tags t ON t.id = at2.tag_id
WHERE
    (
        $2::TEXT IS NULL
        OR EXISTS (
            SELECT 1
            FROM article_tags at3
                JOIN tags t3 ON t3.id = at3.tag_id
            WHERE at3.article_id = a.id
              AND t3.name = $2
        )
    )
    AND (
        $3::TEXT IS NULL
        OR u.username = $3
    )
    AND (
        $4::TEXT IS NULL
        OR EXISTS (
            SELECT 1
            FROM favorites fav2
                JOIN users u2 ON u2.id = fav2.user_id
            WHERE fav2.article_id = a.id
              AND u2.username = $4
        )
    )
GROUP BY
    a.id, u.id, u.username, u.bio, u.image
ORDER BY
    a.created_at DESC
LIMIT $6
OFFSET $5
`

type ListArticlesParams struct {
	CurrentUserID *int64  `json:"current_user_id"`
	Tag           *string `json:"tag"`
	Author        *string `json:"author"`
	FavoritedBy   *string `json:"favorited_by"`
	Offset        int32   `json:"offset"`
	Limit         int32   `json:"limit"`
}

type ListArticlesRow struct {
	Slug            string    `json:"slug"`
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	AuthorUsername  string    `json:"author_username"`
	AuthorBio       *string   `json:"author_bio"`
	AuthorImage     *string   `json:"author_image"`
	AuthorFollowing bool      `json:"author_following"`
	Favorited       bool      `json:"favorited"`
	FavoritesCount  int64     `json:"favorites_count"`
	TagList         []string  `json:"tag_list"`
	TotalCount      int64     `json:"total_count"`
}

func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]*ListArticlesRow, error) {
	rows, err := q.db.Query(ctx, listArticles,
		arg.CurrentUserID,
		arg.Tag,
		arg.Author,
		arg.FavoritedBy,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListArticlesRow
	for rows.Next() {
		var i ListArticlesRow
		if err := rows.Scan(
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorBio,
			&i.AuthorImage,
			&i.AuthorFollowing,
			&i.Favorited,
			&i.FavoritesCount,
			&i.TagList,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByArticleID = `-- name: ListCommentsByArticleID :many
SELECT
    c.id,
    c.body,
    c.created_at,
    c.updated_at,
    u.username AS author_username,
    u.bio AS author_bio,
    u.image AS author_image,
    EXISTS (
        SELECT 1
        FROM follows f
        WHERE f.follower_id = $1
          AND f.followee_id = u.id
    ) AS author_following
FROM
    comments c
    JOIN users u ON u.id = c.author_id
WHERE
    c.article_id = $2
ORDER BY
    c.created_at ASC
`

type ListCommentsByArticleIDParams struct {
	CurrentUserID *int64 `json:"current_user_id"`
	ArticleID     int64  `json:"article_id"`
}

type ListCommentsByArticleIDRow struct {
	ID              int64     `json:"id"`
	Body            string    `json:"body"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	AuthorUsername  string    `json:"author_username"`
	AuthorBio       *string   `json:"author_bio"`
	AuthorImage     *string   `json:"author_image"`
	AuthorFollowing bool      `json:"author_following"`
}

func (q *Queries) ListCommentsByArticleID(ctx context.Context, arg ListCommentsByArticleIDParams) ([]*ListCommentsByArticleIDRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByArticleID, arg.CurrentUserID, arg.ArticleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListCommentsByArticleIDRow
	for rows.Next() {
		var i ListCommentsByArticleIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorBio,
			&i.AuthorImage,
			&i.AuthorFollowing,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedArticles = `-- name: ListFeedArticles :many
SELECT
    a.slug,
    a.title,
    a.description,
    a.created_at,
    a.updated_at,
    u.username AS author_username,
    u.bio AS author_bio,
    u.image AS author_image,
    TRUE::BOOLEAN AS author_following,
    EXISTS (
        SELECT 1
        FROM favorites fav
        WHERE fav.user_id = $1
          AND fav.article_id = a.id
    ) AS favorited,
    (
        SELECT COUNT(*)
        FROM favorites fav
        WHERE fav.article_id = a.id
    ) AS favorites_count,
    COALESCE(
        ARRAY_AGG(t.name ORDER BY t.name) FILTER (WHERE t.name IS NOT NULL),
        '{}'
    )::TEXT[] AS tag_list,
    COUNT(*) OVER ()::BIGINT AS total_count
FROM
    articles a
    JOIN users u ON u.id = a.author_id
    JOIN follows f ON f.followee_id = a.author_id
        AND f.follower_id = $1
    LEFT JOIN article_tags at2 ON at2.article_id = a.id
    LEFT JOIN tags t ON t.id = at2.tag_id
GROUP BY
    a.id, u.id, u.username, u.bio, u.image
ORDER BY
    a.created_at DESC
LIMIT $3
OFFSET $2
`

type ListFeedArticlesParams struct {
	CurrentUserID int64 `json:"current_user_id"`
	Offset        int32 `json:"offset"`
	Limit         int32 `json:"limit"`
}

type ListFeedArticlesRow struct {
	Slug            string    `json:"slug"`
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	AuthorUsername  string    `json:"author_username"`
	AuthorBio       *string   `json:"author_bio"`
	AuthorImage     *string   `json:"author_image"`
	AuthorFollowing bool      `json:"author_following"`
	Favorited       bool      `json:"favorited"`
	FavoritesCount  int64     `json:"favorites_count"`
	TagList         []string  `json:"tag_list"`
	TotalCount      int64     `json:"total_count"`
}

func (q *Queries) ListFeedArticles(ctx context.Context, arg ListFeedArticlesParams) ([]*ListFeedArticlesRow, error) {
	rows, err := q.db.Query(ctx, listFeedArticles, arg.CurrentUserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListFeedArticlesRow
	for rows.Next() {
		var i ListFeedArticlesRow
		if err := rows.Scan(
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorBio,
			&i.AuthorImage,
			&i.AuthorFollowing,
			&i.Favorited,
			&i.FavoritesCount,
			&i.TagList,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT DISTINCT
    name
FROM
    tags
ORDER BY
    name
`

func (q *Queries) ListTags(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfavoriteArticle = `-- name: UnfavoriteArticle :exec
DELETE FROM favorites
WHERE
    user_id = $1
    AND article_id = $2
`

type UnfavoriteArticleParams struct {
	UserID    int64 `json:"user_id"`
	ArticleID int64 `json:"article_id"`
}

func (q *Queries) UnfavoriteArticle(ctx context.Context, arg UnfavoriteArticleParams) error {
	_, err := q.db.Exec(ctx, unfavoriteArticle, arg.UserID, arg.ArticleID)
	return err
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles
SET
    title       = COALESCE($1, title),
    description = COALESCE($2, description),
    body        = COALESCE($3, body),
    updated_at  = now()
WHERE
    slug = $4
RETURNING id, slug, title, description, body, author_id, created_at, updated_at
`

type UpdateArticleParams struct {
	Title       *string `json:"title"`
	Description *string `json:"description"`
	Body        *string `json:"body"`
	Slug        string  `json:"slug"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (*Article, error) {
	row := q.db.QueryRow(ctx, updateArticle,
		arg.Title,
		arg.Description,
		arg.Body,
		arg.Slug,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Body,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (
    name
) VALUES (
    $1
)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

func (q *Queries) UpsertTag(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, upsertTag, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
