// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	AddArticleTag(ctx context.Context, arg AddArticleTagParams) error
	ClearArticleTags(ctx context.Context, articleID int64) error
	CreateArticle(ctx context.Context, arg CreateArticleParams) (*Article, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (*Comment, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error)
	DeleteArticle(ctx context.Context, slug string) error
	DeleteComment(ctx context.Context, id int64) error
	FavoriteArticle(ctx context.Context, arg FavoriteArticleParams) error
	FindArticleRefBySlug(ctx context.Context, slug string) (*FindArticleRefBySlugRow, error)
	FindByEmail(ctx context.Context, email string) (*User, error)
	FindByID(ctx context.Context, id int64) (*FindByIDRow, error)
	FindCommentRefByID(ctx context.Context, id int64) (*FindCommentRefByIDRow, error)
	FindIDByUsername(ctx context.Context, username string) (int64, error)
	FindProfileByUsername(ctx context.Context, arg FindProfileByUsernameParams) (*FindProfileByUsernameRow, error)
	Follow(ctx context.Context, arg FollowParams) error
	GetArticleBySlug(ctx context.Context, arg GetArticleBySlugParams) (*GetArticleBySlugRow, error)
	GetCommentByID(ctx context.Context, arg GetCommentByIDParams) (*GetCommentByIDRow, error)
	ListArticles(ctx context.Context, arg ListArticlesParams) ([]*ListArticlesRow, error)
	ListCommentsByArticleID(ctx context.Context, arg ListCommentsByArticleIDParams) ([]*ListCommentsByArticleIDRow, error)
	ListFeedArticles(ctx context.Context, arg ListFeedArticlesParams) ([]*ListFeedArticlesRow, error)
	ListTags(ctx context.Context) ([]string, error)
	UnfavoriteArticle(ctx context.Context, arg UnfavoriteArticleParams) error
	Unfollow(ctx context.Context, arg UnfollowParams) error
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) (*Article, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (*UpdateUserRow, error)
	UpsertTag(ctx context.Context, name string) (int64, error)
}

var _ Querier = (*Queries)(nil)
