// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package repository

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, email, password
) VALUES (
    $1, $2, $3
) 
RETURNING id, username, email, bio, image, created_at, updated_at
`

type CreateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CreateUserRow struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Bio       *string   `json:"bio"`
	Image     *string   `json:"image"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.Password)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Bio,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const findByEmail = `-- name: FindByEmail :one
SELECT
    id, email, password, username, bio, image, created_at, updated_at
FROM
    users
WHERE
    email = $1
`

func (q *Queries) FindByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRow(ctx, findByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Username,
		&i.Bio,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const findByID = `-- name: FindByID :one
SELECT
    id, username, email, bio, image, created_at, updated_at
FROM
    users
WHERE
    id = $1
`

type FindByIDRow struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Bio       *string   `json:"bio"`
	Image     *string   `json:"image"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) FindByID(ctx context.Context, id int64) (*FindByIDRow, error) {
	row := q.db.QueryRow(ctx, findByID, id)
	var i FindByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Bio,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const findIDByUsername = `-- name: FindIDByUsername :one
SELECT
    id
FROM
    users
WHERE
    username = $1
`

func (q *Queries) FindIDByUsername(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRow(ctx, findIDByUsername, username)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findProfileByUsername = `-- name: FindProfileByUsername :one
SELECT
    u.username,
    u.bio,
    u.image,
    EXISTS (
        SELECT 1
        FROM follows f
        WHERE f.follower_id = $2
          AND f.followee_id = u.id
    ) AS following
FROM
    users u
WHERE
    u.username = $1
`

type FindProfileByUsernameParams struct {
	Username      string `json:"username"`
	CurrentUserID *int64 `json:"current_user_id"`
}

type FindProfileByUsernameRow struct {
	Username  string  `json:"username"`
	Bio       *string `json:"bio"`
	Image     *string `json:"image"`
	Following bool    `json:"following"`
}

func (q *Queries) FindProfileByUsername(ctx context.Context, arg FindProfileByUsernameParams) (*FindProfileByUsernameRow, error) {
	row := q.db.QueryRow(ctx, findProfileByUsername, arg.Username, arg.CurrentUserID)
	var i FindProfileByUsernameRow
	err := row.Scan(
		&i.Username,
		&i.Bio,
		&i.Image,
		&i.Following,
	)
	return &i, err
}

const follow = `-- name: Follow :exec
INSERT INTO follows (
    follower_id, followee_id
) VALUES (
    $1, $2
)
ON CONFLICT DO NOTHING
`

type FollowParams struct {
	FollowerID int64 `json:"follower_id"`
	FolloweeID int64 `json:"followee_id"`
}

func (q *Queries) Follow(ctx context.Context, arg FollowParams) error {
	_, err := q.db.Exec(ctx, follow, arg.FollowerID, arg.FolloweeID)
	return err
}

const unfollow = `-- name: Unfollow :exec
DELETE FROM follows
WHERE
    follower_id = $1
    AND followee_id = $2
`

type UnfollowParams struct {
	FollowerID int64 `json:"follower_id"`
	FolloweeID int64 `json:"followee_id"`
}

func (q *Queries) Unfollow(ctx context.Context, arg UnfollowParams) error {
	_, err := q.db.Exec(ctx, unfollow, arg.FollowerID, arg.FolloweeID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    username   = COALESCE($1, username),
    email      = COALESCE($2, email),
    password   = COALESCE($3, password),
    bio        = CASE WHEN $4::bool THEN $5 ELSE bio END,
    image      = CASE WHEN $6::bool THEN $7 ELSE image END,
    updated_at = now()
WHERE
    id = $8
RETURNING id, username, email, bio, image, created_at, updated_at
`

type UpdateUserParams struct {
	Username *string `json:"username"`
	Email    *string `json:"email"`
	Password *string `json:"password"`
	BioSet   bool    `json:"bio_set"`
	Bio      *string `json:"bio"`
	ImageSet bool    `json:"image_set"`
	Image    *string `json:"image"`
	ID       int64   `json:"id"`
}

type UpdateUserRow struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Bio       *string   `json:"bio"`
	Image     *string   `json:"image"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (*UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.BioSet,
		arg.Bio,
		arg.ImageSet,
		arg.Image,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Bio,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
